### ISSUE TITLE
The tooltip for Grouped bar chart gets cut. How to make the tooltip fully visible ?

### ISSUE THREAD

**Issue by nachiketglobant** [britecharts/britecharts#644] opened 2018-07-17 07:11 UTC
## Expected Behavior
The tooltip should be fully displayed and should not be cut

## Current Behavior
The tooltip appears to be cut

## Possible Solution
Set ZIndex for tooltip control

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/18402874/42801839-9699adae-89be-11e8-94f6-137236f1bd8c.png)

## Context
We have used Britecharts and our QA has logged this defect. Can you please help ?
We have tried setting the Z Index in
    .britechart-tooltip {
      z-index: 9999;
}
but it does not work.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment] 2018-07-17 21:50
Hi @nachiketglobant, thanks for opening this issue!

Actually, z-index won't help. The problem is that it seems we are listening for mouse events on the whole chart container instead of only in the bar stacks or the bars.

It is a bug and we should fix it.

Thanks for your contribution!

**Comment by nachiketglobant** [comment] 2018-07-18 06:39
Hello @Golodhros 

While I fixed this one by updating the 'overflow' to 'visible' for the svg. 
![image](https://user-images.githubusercontent.com/18402874/42863972-6f36e23a-8a82-11e8-8dce-905417dfe2ec.png)

The tooltip displays in the chart area but gets cut outside the chart parent div;
![image](https://user-images.githubusercontent.com/18402874/42864114-f172da42-8a82-11e8-8f39-3aabd4efb26e.png)

Is there a minimum width required for the parent div of the britecharts graphs, that needs to be set in order to render and display the tooltips correctly ?

Thanks for your help.

**Comment by Golodhros** [comment] 2018-07-19 14:54
Hi @nachiketglobant, thanks for following up with this issue!

That's a good patch indeed! I am sure if someone else has this issue that solution will be useful.

There is indeed a moment where the tooltips aren't supposed to be shown due to space limitations. We have left that open to interpretation, so you can use the [Tooltip Threshold](http://eventbrite.github.io/britecharts/module-Grouped-bar.html#.tooltipThreshold__anchor) to set it yourself.

**Comment by nachiketglobant** [comment] 2018-07-20 08:21
As I understand, the tooltip threshold is to set the maximum width of the graph for which the tooltip has to be shown.
Even if we set it, the tooltip gets cut outside the chart container area.
Previously, it was getting cut within the chart container too, and so I added the 'overflow':'visible' fix. 
But outside the chart container area, the overflow wont work.

**Comment by Golodhros** [comment] 2018-07-20 22:21
Hi @nachiketglobant,

Yes, you are right, this is still a bug we should fix!

**Comment by Golodhros** [comment] 2018-09-22 05:36
related to #113

**Comment by Golodhros** [comment] 2021-11-21 19:51
This will be partially fixed on #974, but the root cause (the lack of collision detection logic) won't be solved until we move to use the mini-tooltip or update the tooltip with the missing logic. That would be the work to be done on #113.

**Closed** 2021-11-21 19:51 UTC
Labels: Type: Bug, help wanted, good first issue, Status: Ready to Go
